INSERT INTO Users (Name, Email, Token, ValidToken) VALUES
('John Doe', 'john_doe@example.com', 'aBcDeFgH1234567890', false),
('Alice Johnson', 'alice_johnson@example.com', 'qWeRtYui0987654321', false),
('Michael Smith', 'michael_smith@example.com', 'zXcVbNm5432109876', false),
('Emily Brown', 'emily_brown@example.com', 'pOiUyTrE9876543210', false),
('David Miller', 'david_miller@example.com', 'mNoPkLjI8765432109', false),


INSERT INTO Cards (ID_User, Title, Epic, Description, Type, Priority, State, Backlog, DateCreated, StoryPoints, Category) VALUES
(1, 'Configuración del servidor de base de datos', 'Configuración de Infraestructura', 'Configurar el servidor de base de datos para optimizar el rendimiento del sistema', 'Tarea', 'Media', 'Pendiente', true, CURRENT_TIMESTAMP, 1.5, 'Proyectos'),
(2, 'Implementación de sistema de autenticación', 'Seguridad de la Aplicación', 'Implementar un sistema de autenticación robusto para garantizar la seguridad de la aplicación', 'Tarea', 'Alta', 'Proceso', false, CURRENT_TIMESTAMP, 3.0, 'Roadmap'),
(3, 'Corrección de errores de inicio de sesión', 'Inicio de Sesión', 'Resolver errores relacionados con el proceso de inicio de sesión en la plataforma', 'Error', 'Alta', 'Revisar', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(4, 'Despliegue de actualizaciones de software', 'Despliegue de Software', 'Desplegar las últimas actualizaciones de software en los servidores de producción', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.0, 'Proyectos'),
(5, 'Pruebas de integración del módulo de pagos', 'Integración de Pagos', 'Realizar pruebas de integración del módulo de pagos con los sistemas existentes', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.5, 'Roadmap'),
(1, 'Desarrollo de panel de administración', 'Desarrollo de Aplicación', 'Desarrollar un panel de administración para gestionar usuarios y configuraciones', 'Tarea', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 4.0, 'Proyectos'),
(2, 'Optimización de consultas SQL', 'Optimización de Base de Datos', 'Optimizar las consultas SQL para mejorar el rendimiento de las consultas', 'Tarea', 'Media', 'Pendiente', false, CURRENT_TIMESTAMP, 2.5, 'Roadmap'),
(3, 'Revisión de código de funciones críticas', 'Revisión de Código', 'Realizar una revisión exhaustiva del código de las funciones críticas del sistema', 'Tarea', 'Baja', 'Proceso', false, CURRENT_TIMESTAMP, 1.5, 'Roadmap'),
(4, 'Actualización de documentación de API', 'Documentación de API', 'Actualizar la documentación de la API para reflejar los cambios recientes en la plataforma', 'Tarea', 'Media', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(5, 'Solución de errores en proceso de registro', 'Registro de Usuarios', 'Identificar y corregir errores en el proceso de registro de nuevos usuarios', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.0, 'Roadmap'),
(1, 'Diseño de interfaz de usuario para módulo de ventas', 'Diseño de UI', 'Diseñar la interfaz de usuario para el nuevo módulo de ventas de la plataforma', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.0, 'Roadmap'),
(2, 'Implementación de sistema de notificaciones', 'Notificaciones', 'Implementar un sistema de notificaciones para informar a los usuarios sobre eventos importantes', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 4.0, 'Proyectos'),
(3, 'Corrección de errores en proceso de pago', 'Proceso de Pago', 'Identificar y corregir errores en el proceso de pago de la plataforma', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.5, 'Proyectos'),
(4, 'Revisión de código para cumplimiento de estándares', 'Revisión de Código', 'Revisar el código para garantizar el cumplimiento de los estándares de codificación', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(5, 'Despliegue de actualizaciones de seguridad', 'Seguridad de la Aplicación', 'Desplegar actualizaciones de seguridad para proteger la plataforma contra amenazas conocidas', 'Tarea', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(1, 'Corrección de errores en proceso de envío de correos', 'Envío de Correos', 'Identificar y corregir errores en el proceso de envío de correos electrónicos automáticos', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.0, 'Roadmap'),
(2, 'Mejora de rendimiento de consultas de base de datos', 'Optimización de Base de Datos', 'Optimizar el rendimiento de las consultas de base de datos para reducir el tiempo de respuesta', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.5, 'Proyectos'),
(3, 'Desarrollo de nuevas funcionalidades para módulo de inventario', 'Desarrollo de Aplicación', 'Desarrollar nuevas funcionalidades para el módulo de inventario de la plataforma', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 4.0, 'Roadmap'),
(4, 'Solución de errores en proceso de exportación de datos', 'Exportación de Datos', 'Identificar y corregir errores en el proceso de exportación de datos de la plataforma', 'Error', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 2.5, 'Roadmap'),
(5, 'Refactorización de código para mejorar mantenibilidad', 'Refactorización de Código', 'Refactorizar el código existente para mejorar su mantenibilidad y escalabilidad', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Roadmap'),
(1, 'Desarrollo de sistema de gestión de tareas internas', 'Desarrollo de Aplicación', 'Desarrollar un sistema de gestión de tareas internas para mejorar la eficiencia operativa', 'Tarea', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(2, 'Corrección de errores en proceso de registro de eventos', 'Registro de Eventos', 'Identificar y corregir errores en el proceso de registro de eventos de la plataforma', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(3, 'Despliegue de actualizaciones de software', 'Despliegue de Software', 'Desplegar las últimas actualizaciones de software en los servidores de producción', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.5, 'Roadmap'),
(4, 'Desarrollo de módulo de generación de informes', 'Desarrollo de Aplicación', 'Desarrollar un módulo de generación de informes para proporcionar datos analíticos a los usuarios', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 4.0, 'Proyectos'),
(5, 'Corrección de errores en proceso de validación de formularios', 'Validación de Formularios', 'Identificar y corregir errores en el proceso de validación de formularios de la plataforma', 'Error', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(1, 'Tarea de documentación de código', 'Documentación de Código', 'Documentar el código para facilitar su comprensión y mantenimiento en el futuro', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.5, 'Roadmap'),
(2, 'Desarrollo de sistema de gestión de contenido', 'Desarrollo de Aplicación', 'Desarrollar un sistema de gestión de contenido para administrar el contenido multimedia de la plataforma', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Roadmap'),
(3, 'Corrección de errores en proceso de autenticación', 'Autenticación', 'Identificar y corregir errores en el proceso de autenticación de usuarios en la plataforma', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.5, 'Proyectos'),
(4, 'Optimización de consultas SQL', 'Optimización de Base de Datos', 'Optimizar las consultas SQL para mejorar el rendimiento de la plataforma', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(5, 'Desarrollo de módulo de gestión de proyectos', 'Desarrollo de Aplicación', 'Desarrollar un módulo de gestión de proyectos para organizar y monitorear el progreso de los proyectos internos', 'Tarea', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(1, 'Configuración de servidor de correo electrónico', 'Infraestructura de Comunicaciones', 'Configurar el servidor de correo electrónico para gestionar la comunicación interna y externa de la empresa', 'Tarea', 'Media', 'Pendiente', true, CURRENT_TIMESTAMP, 1.5, 'Proyectos'),
(2, 'Desarrollo de sistema de gestión de empleados', 'Gestión de Recursos Humanos', 'Desarrollar un sistema de gestión de empleados para administrar el personal de la empresa', 'Tarea', 'Alta', 'Proceso', false, CURRENT_TIMESTAMP, 3.0, 'Roadmap'),
(3, 'Corrección de errores en proceso de facturación', 'Facturación', 'Identificar y corregir errores en el proceso de facturación de la empresa', 'Error', 'Alta', 'Revisar', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(4, 'Despliegue de actualizaciones de software', 'Despliegue de Software', 'Desplegar las últimas actualizaciones de software en los servidores de producción', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.0, 'Proyectos'),
(5, 'Pruebas de rendimiento del servidor web', 'Rendimiento de Servidor', 'Realizar pruebas de rendimiento del servidor web para garantizar una experiencia fluida para los usuarios', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.5, 'Roadmap'),
(1, 'Desarrollo de módulo de gestión de clientes', 'Gestión de Clientes', 'Desarrollar un módulo de gestión de clientes para administrar la relación con los clientes de la empresa', 'Tarea', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 4.0, 'Roadmap'),
(2, 'Optimización de consultas SQL', 'Optimización de Base de Datos', 'Optimizar las consultas SQL para mejorar el rendimiento de la plataforma', 'Tarea', 'Media', 'Pendiente', false, CURRENT_TIMESTAMP, 2.5, 'Proyectos'),
(3, 'Revisión de código de funcionalidades críticas', 'Revisión de Código', 'Realizar una revisión exhaustiva del código de las funcionalidades críticas de la plataforma', 'Tarea', 'Baja', 'Proceso', false, CURRENT_TIMESTAMP, 1.5, 'Proyectos'),
(4, 'Actualización de documentación de API', 'Documentación de API', 'Actualizar la documentación de la API para reflejar los cambios recientes en la plataforma', 'Tarea', 'Media', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Proyectos'),
(5, 'Solución de errores en proceso de registro de usuarios', 'Registro de Usuarios', 'Identificar y corregir errores en el proceso de registro de nuevos usuarios', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(1, 'Diseño de interfaz de usuario para módulo de inventario', 'Diseño de UI', 'Diseñar la interfaz de usuario para el módulo de inventario de la plataforma', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.0, 'Proyectos'),
(2, 'Implementación de sistema de alertas de seguridad', 'Seguridad de la Aplicación', 'Implementar un sistema de alertas de seguridad para detectar y prevenir posibles amenazas', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 4.0, 'Roadmap'),
(3, 'Corrección de errores en proceso de pago', 'Proceso de Pago', 'Identificar y corregir errores en el proceso de pago de la plataforma', 'Error', 'Alta', 'Pendiente', false, CURRENT_TIMESTAMP, 2.5, 'Proyectos'),
(4, 'Revisión de código para cumplimiento de estándares', 'Revisión de Código', 'Revisar el código para garantizar el cumplimiento de los estándares de codificación', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Roadmap'),
(5, 'Despliegue de actualizaciones de seguridad', 'Seguridad de la Aplicación', 'Desplegar las últimas actualizaciones de seguridad en los servidores de la aplicación', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.5, 'Proyectos'),
(1, 'Desarrollo de módulo de gestión de proyectos internos', 'Gestión de Proyectos', 'Desarrollar un módulo de gestión de proyectos internos para optimizar la colaboración entre equipos', 'Tarea', 'Alta', 'Proceso', false, CURRENT_TIMESTAMP, 4.0, 'Proyectos'),
(2, 'Corrección de errores en proceso de exportación de datos', 'Exportación de Datos', 'Identificar y corregir errores en el proceso de exportación de datos de la plataforma', 'Error', 'Alta', 'Revisar', true, CURRENT_TIMESTAMP, 3.5, 'Roadmap'),
(3, 'Desarrollo de sistema de notificaciones en tiempo real', 'Notificaciones', 'Desarrollar un sistema de notificaciones en tiempo real para informar a los usuarios sobre eventos importantes', 'Tarea', 'Media', 'Proceso', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos'),
(4, 'Configuración de sistema de monitoreo de servidores', 'Monitoreo de Servidores', 'Configurar un sistema de monitoreo de servidores para supervisar el rendimiento y la disponibilidad', 'Tarea', 'Baja', 'Listo', true, CURRENT_TIMESTAMP, 1.5, 'Roadmap'),
(5, 'Desarrollo de panel de administración de usuarios', 'Administración de Usuarios', 'Desarrollar un panel de administración de usuarios para gestionar los permisos y accesos de los usuarios', 'Tarea', 'Media', 'Pendiente', false, CURRENT_TIMESTAMP, 2.0, 'Proyectos');

INSERT INTO Comments (ID_Card, ID_User, Date, Content, ID_Parent) VALUES
(1, 1, CURRENT_TIMESTAMP, 'Este es un comentario de prueba', NULL),
(1, 2, CURRENT_TIMESTAMP, '¡Excelente trabajo!', NULL),
(2, 3, CURRENT_TIMESTAMP, '¿Alguien necesita ayuda con esto?', NULL),
(2, 4, CURRENT_TIMESTAMP, 'Sí, puedo ayudarte. ¿Qué necesitas?', 3),
(2, 5, CURRENT_TIMESTAMP, 'Gracias por ofrecerte. ¿Podrías revisar este punto específico?', 4),
(3, 1, CURRENT_TIMESTAMP, 'Este error parece ser un problema importante', NULL),
(4, 2, CURRENT_TIMESTAMP, 'Comenzaré a trabajar en esta tarea', NULL),
(5, 3, CURRENT_TIMESTAMP, 'He encontrado un problema en este punto', NULL),
(5, 4, CURRENT_TIMESTAMP, '¿Puedo ayudarte a solucionarlo?', 8),
(5, 5, CURRENT_TIMESTAMP, 'Sí, sería genial si pudieras ayudar', 9),
(6, 1, CURRENT_TIMESTAMP, '¿Alguien ha revisado esta historia de usuario?', NULL),
(7, 2, CURRENT_TIMESTAMP, 'Este error debe resolverse lo antes posible', NULL),
(7, 3, CURRENT_TIMESTAMP, 'Estoy trabajando en ello', 12),
(8, 4, CURRENT_TIMESTAMP, '¿Hay algo más que necesitemos agregar a esta tarea?', NULL),
(9, 5, CURRENT_TIMESTAMP, '¡Hecho! La tarea ha sido completada', NULL),
(10, 1, CURRENT_TIMESTAMP, 'Este error no parece ser tan crítico', NULL),
(11, 2, CURRENT_TIMESTAMP, 'He comenzado a trabajar en el diseño', NULL),
(11, 3, CURRENT_TIMESTAMP, '¿Necesitas alguna ayuda con eso?', 17),
(12, 4, CURRENT_TIMESTAMP, '¿Alguien más ha revisado esta historia de usuario?', NULL),
(12, 5, CURRENT_TIMESTAMP, 'Sí, he revisado la historia de usuario y parece estar bien', 19),
(13, 1, CURRENT_TIMESTAMP, '¿Hay algún progreso en la resolución de este error?', NULL),
(14, 2, CURRENT_TIMESTAMP, '¡Bien hecho! La documentación ha sido completada', NULL),
(15, 3, CURRENT_TIMESTAMP, '¿Qué más necesitamos hacer para esta historia de usuario?', NULL),
(16, 4, CURRENT_TIMESTAMP, 'Estoy investigando la causa de este error', NULL),
(17, 5, CURRENT_TIMESTAMP, 'La optimización ha sido realizada con éxito', NULL),
(18, 1, CURRENT_TIMESTAMP, '¡La nueva funcionalidad ha sido implementada!', NULL),
(19, 2, CURRENT_TIMESTAMP, 'Estoy revisando el código para mejorar su calidad', NULL),
(20, 3, CURRENT_TIMESTAMP, 'Este error está afectando a múltiples usuarios', NULL),
(20, 4, CURRENT_TIMESTAMP, '¿Podemos solucionarlo rápidamente?', NULL),
(20, 5, CURRENT_TIMESTAMP, 'Sí, trabajaremos en ello de inmediato', NULL),
(21, 1, CURRENT_TIMESTAMP, '¿Hay alguna actualización sobre esta historia de usuario?', NULL),
(22, 2, CURRENT_TIMESTAMP, '¡El sistema de pagos está funcionando correctamente ahora!', NULL),
(23, 3, CURRENT_TIMESTAMP, '¡Las nuevas funciones han sido implementadas con éxito!', NULL),
(24, 4, CURRENT_TIMESTAMP, 'Estoy buscando la mejor manera de resolver este error', NULL),
(25, 5, CURRENT_TIMESTAMP, '¿Hay algo más que necesitemos agregar a esta tarea?', NULL),
(26, 1, CURRENT_TIMESTAMP, '¡La revisión de seguridad ha sido completada satisfactoriamente!', NULL),
(27, 2, CURRENT_TIMESTAMP, 'Estamos investigando la causa de este error', NULL),
(27, 3, CURRENT_TIMESTAMP, '¡El código ha sido refactorizado y mejorado!', 37),
(28, 4, CURRENT_TIMESTAMP, '¿Hay algún avance en la resolución de este error?', NULL),
(29, 5, CURRENT_TIMESTAMP, '¡La mejora de rendimiento ha sido exitosa!', NULL),
(30, 1, CURRENT_TIMESTAMP, '¿Alguien puede ayudar con este error?', NULL),
(30, 2, CURRENT_TIMESTAMP, 'Sí, estoy disponible para ayudar', 41),
(30, 3, CURRENT_TIMESTAMP, '¡Gracias por tu ayuda!', 42),
(31, 4, CURRENT_TIMESTAMP, '¡El proceso de exportación de datos ahora es más eficiente!', NULL),
(32, 5, CURRENT_TIMESTAMP, '¡La refactorización de código ha mejorado mucho la legibilidad!', NULL),
(33, 1, CURRENT_TIMESTAMP, 'Estamos cerca de resolver este error', NULL),
(33, 2, CURRENT_TIMESTAMP, '¡El proceso de validación de formularios ahora es más sólido!', 46),
(34, 3, CURRENT_TIMESTAMP, '¡El sistema está funcionando sin problemas ahora!', NULL),
(35, 4, CURRENT_TIMESTAMP, '¿Hay alguna tarea pendiente que necesite atención?', NULL),
(36, 5, CURRENT_TIMESTAMP, 'Estoy revisando la documentación para asegurarme de que esté completa', NULL),
(37, 1, CURRENT_TIMESTAMP, '¿Alguien puede proporcionar una actualización sobre este error?', NULL),
(37, 2, CURRENT_TIMESTAMP, '¡El problema ha sido resuelto con éxito!', 51),
(38, 3, CURRENT_TIMESTAMP, 'Estoy investigando un enfoque para resolver este error', NULL),
(39, 4, CURRENT_TIMESTAMP, '¡La nueva funcionalidad ha sido bien recibida por los usuarios!', NULL),
(40, 5, CURRENT_TIMESTAMP, 'Estamos trabajando en una solución para este error', NULL),
(40, 1, CURRENT_TIMESTAMP, '¿Puedo ayudar en algo?', 55),
(40, 2, CURRENT_TIMESTAMP, '¡Claro! Podrías revisar la implementación actual', 56),
(41, 3, CURRENT_TIMESTAMP, '¡La refactorización del código ha mejorado enormemente su mantenibilidad!', NULL),
(42, 4, CURRENT_TIMESTAMP, '¿Hay alguna actualización sobre este error?', NULL),
(42, 5, CURRENT_TIMESTAMP, 'Estamos en proceso de resolverlo', 59),
(43, 1, CURRENT_TIMESTAMP, '¿Alguien puede echar un vistazo rápido a este error?', NULL),
(43, 2, CURRENT_TIMESTAMP, '¡Seguro! Voy a revisarlo ahora mismo', 61),
(44, 3, CURRENT_TIMESTAMP, '¡La exportación de datos se ha vuelto mucho más rápida!', NULL),
(45, 4, CURRENT_TIMESTAMP, 'Estamos buscando formas de mejorar el rendimiento', NULL),
(46, 5, CURRENT_TIMESTAMP, '¿Hay alguna tarea urgente que necesite atención?', NULL),
(47, 1, CURRENT_TIMESTAMP, '¡El código ha sido refactorizado con éxito!', NULL),
(48, 2, CURRENT_TIMESTAMP, '¡El sistema está funcionando sin problemas después de las últimas actualizaciones!', NULL),
(49, 3, CURRENT_TIMESTAMP, '¿Alguien necesita ayuda con algún problema?', NULL),
(50, 4, CURRENT_TIMESTAMP, '¡La documentación está completa y lista para su revisión!', NULL);

INSERT INTO Label (Name) VALUES
('Bug'),
('Mejora'),
('Investigación'),
('Diseño'),
('Documentación'),
('Implementación'),
('Optimización'),
('Revisión de código'),
('Prueba'),
('Despliegue'),
('Seguridad'),
('Prioridad alta'),
('Prioridad media'),
('Prioridad baja'),
('Urgente'),
('Planificado'),
('En progreso'),
('Revisión'),
('Completado'),
('Pendiente');

INSERT INTO LabelCard (ID_Card, ID_Label) VALUES
(1, 10), 
(1, 16), 
(1, 17), 

(2, 11), 
(2, 15), 
(2, 17), 

(3, 1),  
(3, 16), 
(3, 18), 
(4, 9),  
(4, 15), 
(4, 17), 

(5, 9),  
(5, 14), 
(5, 17), 

(6, 11), 
(6, 16), 
(6, 17), 

(7, 1),  
(7, 16), 
(7, 18), 
(8, 14), 
(8, 15), 
(8, 17), 

(9, 14), 
(9, 16), 
(9, 18), 
(10, 10), 
(10, 15), 
(10, 17), 

(11, 11), 
(11, 14), 
(11, 17), 

(12, 1),  
(12, 16), 
(12, 18), 
(13, 9),  
(13, 15), 
(13, 17), 

(14, 9),  
(14, 16), 
(14, 17), 

(15, 11), 
(15, 14), 
(15, 17), 

(16, 1),  
(16, 16), 
(16, 18), 
(17, 14), 
(17, 15), 
(17, 17), 

(18, 14), 
(18, 16), 
(18, 18), 

(19, 10), 
(19, 15), 
(19, 17), 

(20, 11), 
(20, 14), 
(20, 17), 

(21, 1),  
(21, 16), 
(21, 18), 

(22, 9),  
(22, 15), 
(22, 17), 

(23, 9),  
(23, 16), 
(23, 17), 

(24, 11), 
(24, 14), 
(24, 17), 

(25, 1),  
(25, 16), 
(25, 18), 

(26, 14), 
(26, 15), 
(26, 17), 

(27, 14), 
(27, 16), 
(27, 18), 

(28, 10), 
(28, 15), 
(28, 17), 

(29, 11), 
(29, 14), 
(29, 17), 

(30, 1),  
(30, 16), 
(30, 18), 

(31, 9),  
(31, 15), 
(31, 17), 

(32, 9),  
(32, 16), 
(32, 17), 

(33, 11), 
(33, 14), 
(33, 17), 

(34, 1),  
(34, 16), 
(34, 18), 

(35, 14), 
(35, 15), 
(35, 17), 

(36, 14), 
(36, 16), 
(36, 18),

(37, 10), 
(37, 15), 
(37, 17), 

(38, 11), 
(38, 14), 
(38, 17), 

(39, 1),  
(39, 16), 
(39, 18),

(40, 9),  
(40, 15), 
(40, 17), 

(41, 9),  
(41, 16), 
(41, 17), 

(42, 11), 
(42, 14), 
(42, 17), 

(43, 1),  
(43, 16), 
(43, 18), 
(44, 14), 
(44, 15), 
(44, 17), 

(45, 14), 
(45, 16), 
(45, 18), 
(46, 10), 
(46, 15), 
(46, 17), 

(47, 11), 
(47, 14), 
(47, 17), 

(48, 1),  
(48, 16), 
(48, 18), 
(49, 9),  
(49, 15), 
(49, 17), 

(50, 9),  
(50, 16), 
(50, 17); 
