#Docs: https://github.com/kubernetes/helm/blob/master/docs/rbac.md

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: default

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io