{{with .Values.persistentVolume}}

apiVersion: v1
kind: PersistentVolume
metadata:
 name: {{.name}}
 annotations:
   volume.beta.kubernetes.io/storage-class: {{.name}}
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 gcePersistentDisk:
   fsType: ext4
   pdName: {{.gcePdName}}

{{end}}