# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceInfo:
  name: test
  namespace: test
  
image:
  repository: 72horas/test
  tag: 
  pullPolicy: IfNotPresent

configMapPath: "config.json"

# We use services to define the deployments' services that will be created
servicePorts: []
resources: 
  requests:
    cpu: "1m"
    
nodeSelector: {}

tolerations: []

affinity: {}